### ISSUE TITLE
EC Private Key exposed 

### ISSUE THREAD

**Issue by 0xtobu** [folkehelseinstituttet/Fhi.Smittestopp.Backend#1]
The commit **62da018b241801b3176d0ab6f1f4ccb6b7760c09** contains private keys.

file: [DiagnosisKeysServiceTests.cs](https://github.com/folkehelseinstituttet/Fhi.Smittestopp.Backend/blob/master/DIGNDB.App.SmitteStop.Testing/ServiceTest/DiagnosisKeysServiceTests.cs)
file:  [ ExposureBatchFileUtilTests.cs](https://github.com/folkehelseinstituttet/Fhi.Smittestopp.Backend/blob/master/DIGNDB.App.SmitteStop.Testing/UtilTest/ExposureBatchFileUtilTests.cs)

**Comment by flamaniac** [comment]
This is just a test. Certificate is dummy - created for this test only.

**Comment by 0xtobu** [comment]
Awesome! Closing issue
