### ISSUE TITLE
Remove code duplication between `UploadKeysAuthorizationAttribute` and `AuthorizationAttribute`

### ISSUE THREAD

**Issue by matishadow** [folkehelseinstituttet/Fhi.Smittestopp.Backend#28]
Code duplication was intentionally introduced in #25 to minimize the risk of breaking existing functionality.
To keep the code clean it'd be nice to get rid of this code duplication using inheritance or composition pattern.

**Comment by netcompany-martinropcke** [comment]
AuthorizationAttribute has been removed and replaced by UploadKeysAuthorizationAttribute
